// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartsManager.Api.Data;

#nullable disable

namespace PartsManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319083151_AddPriceToMaterial")]
    partial class AddPriceToMaterial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_CurrentStock", b =>
                {
                    b.Property<long>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inv_CurrentStock");

                    b.HasData(
                        new
                        {
                            StockID = 1L,
                            LastUpdated = new DateTime(2026, 1, 28, 17, 2, 24, 0, DateTimeKind.Unspecified),
                            MaterialID = 1,
                            Quantity = 500m,
                            WarehouseID = 1
                        },
                        new
                        {
                            StockID = 2L,
                            LastUpdated = new DateTime(2026, 1, 28, 17, 2, 24, 0, DateTimeKind.Unspecified),
                            MaterialID = 2,
                            Quantity = 1000m,
                            WarehouseID = 1
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_Transactions", b =>
                {
                    b.Property<long>("TransID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AfterQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatorID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inv_Transactions");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Machines", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MachineID");

                    b.ToTable("Mdm_Machines");

                    b.HasData(
                        new
                        {
                            MachineID = 1,
                            MachineCode = "M01",
                            MachineName = "SMT-01"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_MaterialAttachments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Mdm_MaterialAttachments");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Materials", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsPrintLabel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SafeStockQty")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialID");

                    b.ToTable("Mdm_Materials");

                    b.HasData(
                        new
                        {
                            MaterialID = 1,
                            BarCode = "1001",
                            LeadTimeDays = 3,
                            Manufacturer = "None",
                            Name = "M3 Screw",
                            NeedsPrintLabel = true,
                            PartNo = "SCREW-001",
                            Price = 0m,
                            SafeStockQty = 100,
                            SourceType = (byte)0,
                            Specification = "Stainless Steel M3x10",
                            Supplier = "None"
                        },
                        new
                        {
                            MaterialID = 2,
                            BarCode = "1002",
                            LeadTimeDays = 7,
                            Manufacturer = "None",
                            Name = "Resistor 10k",
                            NeedsPrintLabel = true,
                            PartNo = "RES-10K",
                            Price = 0m,
                            SafeStockQty = 500,
                            SourceType = (byte)0,
                            Specification = "10k Ohm 0603",
                            Supplier = "None"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Warehouses", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalMES")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WarehouseID");

                    b.ToTable("Mdm_Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseID = 1,
                            IsExternalMES = false,
                            WarehouseCode = "MainWH",
                            WarehouseName = "主倉庫 (Main)"
                        },
                        new
                        {
                            WarehouseID = 2,
                            IsExternalMES = false,
                            WarehouseCode = "LineSideA",
                            WarehouseName = "線邊倉 A"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Rel_MachineBOM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RotateQty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageQty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsageTiming")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MachineID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Rel_MachineBOM");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Sys_SyncLogs", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.ToTable("Sys_SyncLogs");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Sys_Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PasswordHash");

                    b.Property<int>("UserLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Sys_Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            IsActive = true,
                            PasswordHash = "admin",
                            UserLevel = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_CurrentStock", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartsManager.Api.Entities.Mdm_Warehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_Transactions", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartsManager.Api.Entities.Mdm_Warehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_MaterialAttachments", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Rel_MachineBOM", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Machines", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Material");
                });
#pragma warning restore 612, 618
        }
    }
}
