// <auto-generated />
using System;
using PartsManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PartsManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128090226_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_CurrentStock", b =>
                {
                    b.Property<long>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinLocation")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inv_CurrentStock");

                    b.HasData(
                        new
                        {
                            StockID = 1L,
                            LastUpdated = new DateTime(2026, 1, 28, 17, 2, 24, 882, DateTimeKind.Local).AddTicks(6835),
                            MaterialID = 1,
                            Quantity = 500m,
                            WarehouseID = 1
                        },
                        new
                        {
                            StockID = 2L,
                            LastUpdated = new DateTime(2026, 1, 28, 17, 2, 24, 882, DateTimeKind.Local).AddTicks(6853),
                            MaterialID = 2,
                            Quantity = 1000m,
                            WarehouseID = 1
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_Transactions", b =>
                {
                    b.Property<long>("TransID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AfterQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChangeQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("TransID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Inv_Transactions");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Machines", b =>
                {
                    b.Property<int>("MachineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MachineID");

                    b.ToTable("Mdm_Machines");

                    b.HasData(
                        new
                        {
                            MachineID = 1,
                            MachineCode = "M01",
                            MachineName = "SMT-01"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Materials", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SafeStockQty")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaterialID");

                    b.ToTable("Mdm_Materials");

                    b.HasData(
                        new
                        {
                            MaterialID = 1,
                            BarCode = "1001",
                            Name = "M3 Screw",
                            PartNo = "SCREW-001",
                            SafeStockQty = 100,
                            SourceType = (byte)0
                        },
                        new
                        {
                            MaterialID = 2,
                            BarCode = "1002",
                            Name = "Resistor 10k",
                            PartNo = "RES-10K",
                            SafeStockQty = 500,
                            SourceType = (byte)0
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Mdm_Warehouses", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalMES")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("WarehouseID");

                    b.ToTable("Mdm_Warehouses");

                    b.HasData(
                        new
                        {
                            WarehouseID = 1,
                            IsExternalMES = false,
                            WarehouseCode = "MainWH"
                        },
                        new
                        {
                            WarehouseID = 2,
                            IsExternalMES = false,
                            WarehouseCode = "LineSideA"
                        });
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Rel_MachineBOM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UsageQty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("MachineID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Rel_MachineBOM");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_CurrentStock", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartsManager.Api.Entities.Mdm_Warehouses", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Inv_Transactions", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("PartsManager.Api.Entities.Rel_MachineBOM", b =>
                {
                    b.HasOne("PartsManager.Api.Entities.Mdm_Machines", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartsManager.Api.Entities.Mdm_Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Material");
                });
#pragma warning restore 612, 618
        }
    }
}

