; PartsManager API Server Configuration

[ConnectionStrings]
DefaultConnection=Data Source=D:\SourceCode\CS\PartsManager_GE\DB\Parts.db

[Network]
Urls=http://0.0.0.0:5000

[System]
Language=de
AttachmentPath=Attachments

[Backup]
OAuthClientId=290775409112-94ej7sb8nvfobt6c2g5vqkbv1hpram3k.apps.googleusercontent.com
OAuthClientSecret=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
OAuthRefreshToken=1//04-sreRXdQhZ1CgYIARAAGAQSNwF-L9IrU5ZGSj5Iq-1PPbE5X5SdZd-WS1GOOsVDhDBl7oHRX3tomfPyVMAAzkTeL2KhatpQbWM
DriveParentFolderId=1aV4Fju2OwE_1FS9eJ2EtkUWlYiFfY5pe
BackupIntervalHours=24
MaxRetentionCount=7
