<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <ProjectReference Include="..\PartsManager.Shared\PartsManager.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="bpac">
      <Guid>{90359D74-B7D9-467F-B938-3883F4CAB582}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>3</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="client.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.95.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="config.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="..\doc\ImagePDF.bmp">
      <Link>Resources\PdfIcon.bmp</Link>
      <LogicalName>PdfIcon.bmp</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <Version>1.2.0</Version>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RuntimeIdentifier>win</RuntimeIdentifier>
    <ApplicationIcon>client.ico</ApplicationIcon>
  </PropertyGroup>

</Project>

